/**
 * Collects every visible placeholder block from the built site (data-placeholder attributes)
 * and rewrites section F of docs/placeholders.md. Run after `npm run build`.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { pages, attr } from './lib.mjs';

const why = (slot) => {
  if (slot === 'hero') return 'A 414 px thumbnail cannot fill a hero; full-resolution original needed';
  if (slot === 'inline' || slot === 'feature') return 'No original wide enough for the slot';
  if (slot === 'portrait' || slot === 'crew-more') return 'No portrait or additional crew photography exists';
  if (slot.startsWith('story-')) return 'Unverified fact; stays out of the copy until Sam confirms it';
  if (slot === 'form-endpoint') return 'No email address or form endpoint supplied';
  if (slot === 'blog-posts') return 'No posts written yet';
  if (slot === 'gallery-missing') return 'No photograph of these subjects in the interim set';
  return 'No suitable original in the interim set';
};

const rows = new Map();
for (const page of await pages()) {
  for (const m of page.html.matchAll(/<[a-z]+\s[^>]*data-placeholder[^>]*>/gi)) {
    const tag = m[0];
    const slot = attr(tag, 'data-slot') ?? '?';
    const need = attr(tag, 'data-need') ?? '?';
    const key = `${page.path}|${slot}|${need}`;
    if (!rows.has(key)) rows.set(key, { page: page.path, slot, need });
  }
}
const sorted = [...rows.values()].sort((a, b) => a.page.localeCompare(b.page) || a.slot.localeCompare(b.slot));
const table = ['| Page | Slot | What is needed | Why |', '| --- | --- | --- | --- |', ...sorted.map((r) => `| \`${r.page}\` | ${r.slot} | ${r.need.replace(/\|/g, '\\|')} | ${why(r.slot)} |`)].join('\n');

const docPath = 'docs/placeholders.md';
let doc = await readFile(docPath, 'utf8');
const head = doc.split('## F. Page-level placeholders')[0];
const section = `## F. Page-level placeholders\n\nGenerated by \`node qa/placeholders.mjs\` from the built site on ${new Date().toISOString().slice(0, 10)}: ${sorted.length} visible placeholder blocks across ${new Set(sorted.map((r) => r.page)).size} pages. Every one is a real block on staging with a dashed brick border; none may be "fixed" by inventing content.\n\n${table}\n`;
await writeFile(docPath, head + section);
console.log(`${sorted.length} placeholders on ${new Set(sorted.map((r) => r.page)).size} pages written to ${docPath}`);
